name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - .github/**
      - package.json
      - pnpm-lock.yaml
      - biome.json
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/**
      - package.json
      - pnpm-lock.yaml
      - biome.json
permissions:
  contents: read
  deployments: write
jobs:
  lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - run: pnpm lint
      - run: npx biome check .
